name: Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Check if PR is mergeable
        uses: nwtgck/pull-request-mergeable-action@v2.1.1
        id: pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-non-mergeable: true

      - name: Fail if PR is not mergeable
        run: exit ${{ steps.pr.outputs.non_mergeable }}
